package me.matsumo.travelog.core.model.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GeoRegionDTO(
    val id: String? = null,
    @SerialName("group_id")
    val groupId: String,
    val name: String,
    @SerialName("adm2_id")
    val adm2Id: String,
    @SerialName("name_en")
    val nameEn: String? = null,
    @SerialName("name_ja")
    val nameJa: String? = null,
    val wikipedia: String? = null,
    @SerialName("iso3166_2")
    val iso31662: String? = null,
    @SerialName("thumbnail_url")
    val thumbnailUrl: String? = null,
    /**
     * GeoJSON string of Point, generated by SQL: ST_AsGeoJSON(center::geometry)
     */
    @SerialName("center_geojson")
    val centerGeoJson: String? = null,
    /**
     * GeoJSON string of MultiPolygon, generated by SQL: ST_AsGeoJSON(polygons)
     */
    @SerialName("polygons_geojson")
    val polygonsGeoJson: String? = null,
    @SerialName("created_at")
    val createdAt: String? = null,
    @SerialName("updated_at")
    val updatedAt: String? = null,
)
